openapi: 3.0.3
info:
  title: Test 1 API
  version: 1.0.0
  description: An API for managing tasks.

servers:
  - url: http://localhost:3000

paths:
  /health:
    get:
      summary: Checks the status of the server
      responses:
        "200":
          description: "Server is running correctly."
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
  /api/tasks:
    get:
      summary: Returns all tasks that the server manages
      responses:
        "200":
          description: Successfully returned all tasks to the client
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    post:
        summary: Creates a new task
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskInput"
        responses:
          "201":
            description: Successfully created a new task
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Task"
          "400":
            description: Could not create the new task
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ErrorResponse"

  /api/tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Retrieves an existing task based on the id
      responses:
        "200":
          description: Successfully retrieved a task from the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    put:
      summary: Replaces an existing task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskInput"
      responses:
        "200":
          description: The task was successfully replaced
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    patch:
      summary: Updates a specific field of a task held by the server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskInput"
      
components:
  schemas:
    Task:
      type: object
      required: [id, title, course, completed]
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Complete Test 1
        course:
          type: string
          example: CS-453
        completed:
          type: boolean
          example: true

    TaskInput:
      type: object
      required: [title, course, completed]
      properties:
        title:
          type: string
          example: Complete Test 1
        course:
          type: string
          example: CS-453
        completed:
          type: boolean
          example: true

    TaskPatch:
      type: object
      anyOf: [title, course, completed]
      properties:
        title:
          type: string
          example: Complete Test 1
        course:
          type: string
          example: CS-453
        completed:
          type: boolean
          example: true

    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: string
          example: Task with ID 5 was not found.
